### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by Natsukiw** [yuttyann/ScriptBlockPlus#2]
[18:28:37 ERROR]: Could not pass event PlayerMoveEvent to ScriptBlockPlus v1.5.0
org.bukkit.event.EventException
        at cc.uraniummc.eventexecutor.EventExecutorImp.execute(EventExecutorImp.java:25) ~[EventExecutorImp.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:344) [nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(C03PacketPlayer.java:234) [jf.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:176) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at com.github.yuttyann.scriptblockplus.BlockCoords.<init>(BlockCoords.java:16) ~[?:?]
        at com.github.yuttyann.scriptblockplus.listener.ScriptWalkListener.onPlayerMoveEvent(ScriptWalkListener.java:31) ~[?:?]
        at com.github.yuttyann.scriptblockplus.listener.ScriptWalkListener_482_onPlayerMoveEvent_PlayerMoveEvent.invoke(Uranium) ~[?:?]
        at cc.uraniummc.eventexecutor.EventExecutorImp.execute(EventExecutorImp.java:23) ~[EventExecutorImp.class:1.7.10-R0.1-SNAPSHOT]
        ... 13 more

**Comment by yuttyann** [comment]
I do not know the cause.
I anticipate that you can not acquire the coordinates when the player walked.
Once, we will take countermeasures in the next version.

**Comment by Natsukiw** [comment]
😁3Q

2018-07-23 3:29 GMT+08:00 yuttyann <notifications@github.com>:
