### ISSUE TITLE
1.9.8の対策法も動作しません。

### ISSUE THREAD

**Issue by ShrkSoft** [yuttyann/ScriptBlockPlus#20]
コマンドが動作しない場合の対策法で*を追加しても、以下のエラーログが表示され解決されませんでした。
Spigotバージョン：1.12.2

Could not pass event BlockInteractEvent to ScriptBlockPlus v1.9.8
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-dcd1643-e60fc34]
at com.github.yuttyann.scriptblockplus.listener.InteractListener.callEvent(InteractListener.java:109) [ScriptBlockPlus%20v1.9.8.jar:?]
at com.github.yuttyann.scriptblockplus.listener.InteractListener.onPlayerInteractEvent(InteractListener.java:83) [ScriptBlockPlus%20v1.9.8.jar:?]
at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:953) [?:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/GameRule
at com.github.yuttyann.scriptblockplus.script.option.BaseOption.executeCommand(BaseOption.java:209) ~[?:?]
at com.github.yuttyann.scriptblockplus.script.option.chat.Bypass.isValid(Bypass.java:26) ~[?:?]
at com.github.yuttyann.scriptblockplus.script.option.BaseOption.callOption(BaseOption.java:182) ~[?:?]
at com.github.yuttyann.scriptblockplus.script.ScriptRead.read(ScriptRead.java:123) ~[?:?]
at com.github.yuttyann.scriptblockplus.listener.ScriptInteractListener.onBlockInteractEvent(ScriptInteractListener.java:57) ~[?:?]
at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-dcd1643-e60fc34]

**Comment by yuttyann** [comment]
関係ない部分がエラーを発生させているみたいですね。
1.12.2に存在しない機能を使ってしまったのが原因みたいです。
後日修正しておきます。

**Comment by yuttyann** [comment]
7ed26e20a847907b0af5c3709e9a98f361d7e4b2
