### ISSUE TITLE
sbpコマンドをブロックに置くことが出来ない

### ISSUE THREAD

**Issue by ShrkSoft** [yuttyann/ScriptBlockPlus#21]
Spigotバージョン: 1.12.2　ScriptBlockPlusのバージョン：2.0.1
sbp interact create @bypass <command> で sbpコマンドがブロックに置けない現象が起きています。
看板、ボタンを含む、すべてのブロック、保護の有無関係なく動作しません。
2.0.1以前に作成したコマンドは問題なく動作するが、2.0.1以降でブロックにコマンドを置けません。
walk , interact , break全てでこの現象が起きています。
コマンド作成時及び実行時にエラーログは発生していませんが、EventExceptionでnullエラーが起きているため、そのエラーログも同時に報告させていただきます。

Could not pass event BlockClickEvent to ScriptBlockPlus v2.0.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.github.yuttyann.scriptblockplus.listener.InteractListener.callEvent(InteractListener.java:109) [ScriptBlockPlus_v2.0.1.jar:?]
at com.github.yuttyann.scriptblockplus.listener.InteractListener.onPlayerInteractEvent(InteractListener.java:83) [ScriptBlockPlus_v2.0.1.jar:?]
at sun.reflect.GeneratedMethodAccessor181.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [?:git-Spigot-eb3d921-2b93d83]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_272]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_272]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 27956 path $
at com.google.gson.Gson.assertFullConsumption(Gson.java:863) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.Gson.fromJson(Gson.java:853) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.Gson.fromJson(Gson.java:801) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.Gson.fromJson(Gson.java:773) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.github.yuttyann.scriptblockplus.file.json.Json.load(Json.java:107) ~[?:?]
at com.github.yuttyann.scriptblockplus.file.json.Json.<init>(Json.java:40) ~[?:?]
at com.github.yuttyann.scriptblockplus.file.json.PlayerCount.<init>(PlayerCount.java:19) ~[?:?]
at com.github.yuttyann.scriptblockplus.script.ScriptRead.read(ScriptRead.java:130) ~[?:?]
at com.github.yuttyann.scriptblockplus.listener.ScriptInteractListener.onBlockClickEvent(ScriptInteractListener.java:58) ~[?:?]
at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
... 26 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 27956 path $
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.Gson.assertFullConsumption(Gson.java:859) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.Gson.fromJson(Gson.java:853) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.Gson.fromJson(Gson.java:801) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.google.gson.Gson.fromJson(Gson.java:773) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
at com.github.yuttyann.scriptblockplus.file.json.Json.load(Json.java:107) ~[?:?]
at com.github.yuttyann.scriptblockplus.file.json.Json.<init>(Json.java:40) ~[?:?]
at com.github.yuttyann.scriptblockplus.file.json.PlayerCount.<init>(PlayerCount.java:19) ~[?:?]
at com.github.yuttyann.scriptblockplus.script.ScriptRead.read(ScriptRead.java:130) ~[?:?]
at com.github.yuttyann.scriptblockplus.listener.ScriptInteractListener.onBlockClickEvent(ScriptInteractListener.java:58) ~[?:?]
at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
... 26 more

**Comment by yuttyann** [comment]
検証を行ってみましたが確認できませんでした。
（エラーの原因は".json"系のファイル関係みたいです。）

以下をお試しください。
・Javaのバージョンを8に変更する。
・サーバーの再インストールを行う。
・プラグインの再インストールを行う。
・サーバーの"plugins/ScriptBlockPlus/json"フォルダを削除する。（バックアップ推奨）

問題が解決しない場合は、サーバーの正確なバージョン(/ver)、実行した状況、導入連携プラグインなどの詳細をご連絡ください。

**Comment by ShrkSoft** [comment]
jsonフォルダを削除したところ問題が解決しました。
お手数おかけしました。
