### ISSUE TITLE
Does SBP support paperspigot？

### ISSUE THREAD

**Issue by HySand** [yuttyann/ScriptBlockPlus#29]
Can't pass event to SBPv2.1.1,
Papper 1.16.5,java11

**Comment by yuttyann** [comment]
Yes, SBP supports PaperMC.

**Comment by yuttyann** [comment]
If you are experiencing problems, please describe them in detail.

**Comment by HySand** [comment]
It may be conflict with plugins
 
`
[17:55:43] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to ScriptBlockPlus v2.1.1
java.lang.NumberFormatException: Error at index 2 in: "10-DEV-122"
	at java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:81) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:735) ~[?:?]
	at com.github.yuttyann.scriptblockplus.utils.Utils.getVersionInt(Utils.java:104) ~[?:?]
	at com.github.yuttyann.scriptblockplus.utils.Utils.isUpperVersion(Utils.java:89) ~[?:?]
	at com.github.yuttyann.scriptblockplus.hook.plugin.Placeholder.setPlaceholder(Placeholder.java:56) ~[?:?]
	at com.github.yuttyann.scriptblockplus.hook.plugin.Placeholder.replace(Placeholder.java:74) ~[?:?]
	at com.github.yuttyann.scriptblockplus.script.ScriptRead.perform(ScriptRead.java:148) ~[?:?]
	at com.github.yuttyann.scriptblockplus.script.ScriptRead.read(ScriptRead.java:137) ~[?:?]
	at com.github.yuttyann.scriptblockplus.listener.TriggerListener.onTrigger(TriggerListener.java:209) ~[?:?]
	at com.github.yuttyann.scriptblockplus.listener.TriggerListener.lambda$static$0(TriggerListener.java:52) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-575]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-575]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1409) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-575]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-575]
	at java.lang.Thread.run(Thread.java:834) [?:?]
`

`Plugins (50): ACubelets, AdvancedNMotd, AntiAFKPlus, AreaMusic, BattlePass, Citizens, CometWelcome, CoreProtect, DungeonsXL, eBackup, EffectLib*, FastAsyncWorldEdit (WorldEdit), GlobalGamerules, HolographicDisplays, HyperDrive, IllegalStack, InteractionVisualizer, ItemSwitchSound, LibsDisguises, LightAPI, LoneLibs, LuckPerms, MMOCore, MMOItems, ModelEngine, ModelEngineEX, Multiverse-Core, MythicLib, MythicMobs, Nameplates, NoFishRepair*, PhysicsToGo, PL-Hide-Pro, PlaceholderAPI, PremiumVanish, ProCosmetics, ProtectionStones, ProtocolLib, Realistic_World, RespawnTitle, RPGMoney, ScriptBlockPlus, TAB, Tokens, TrChat, TrMenu, Vault, WorldBorder, WorldGuard, XConomy`

**Comment by yuttyann** [comment]
Probably it is due to the inclusion of non-numeric strings when comparing versions.
Please try installing the latest version of the PlaceholderAPI.
https://www.spigotmc.org/resources/placeholderapi.6245/history
