### ISSUE TITLE
when use cmi , something wrong with [$cost]

### ISSUE THREAD

**Issue by blankpager** [yuttyann/ScriptBlockPlus#38]
appology for my poor english

**Describe the bug**  
When i use essentialsX, server run sbp perfectly.
However,when i change essentials to cmi, there is something wrong with [$cost] 

**Server**  
Type: loliserver/mohist
Version: 1.16.5  
Plugins: essentialsX,CMI,SBP

**To Reproduce**  
change ess to cmi .i'm sure that both of the two plugins work perfectly and vault also work normally.
however,when i use cmi ,[$cost] cannot work right.
For example, /sbp interact create [$cost:100][@bypass /heal], i knock the block ,it doesn't work
I tried sbp v2.0.0 2.2.1 2.2.2, they have the same problem.

**Screenshots**  
![cmi](https://user-images.githubusercontent.com/64553078/158061526-93dad270-f984-484a-8288-3f8ae3ecdc7d.png)

[21:37:06 WARN]: java.lang.UnsupportedOperationException: Invalid function
[21:37:06 WARN]:        at com.github.yuttyann.scriptblockplus.script.option.vault.MoneyCost.isValid(MoneyCost.java:37)
[21:37:06 WARN]:        at com.github.yuttyann.scriptblockplus.script.option.BaseOption.callOption(BaseOption.java:243)
[21:37:06 WARN]:        at com.github.yuttyann.scriptblockplus.script.ScriptRead.perform(ScriptRead.java:240)
[21:37:06 WARN]:        at com.github.yuttyann.scriptblockplus.script.ScriptRead.read(ScriptRead.java:218)
[21:37:06 WARN]:        at com.github.yuttyann.scriptblockplus.listener.TriggerListener.onTrigger(TriggerListener.java:209)
[21:37:06 WARN]:        at com.github.yuttyann.scriptblockplus.listener.TriggerListener.lambda$0(TriggerListener.java:52)
[21:37:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[21:37:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:37:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588)
[21:37:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573)
[21:37:06 WARN]:        at com.github.yuttyann.scriptblockplus.listener.InteractListener.callEvent(InteractListener.java:125)
[21:37:06 WARN]:        at com.github.yuttyann.scriptblockplus.listener.InteractListener.onPlayerInteract(InteractListener.java:86)
[21:37:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[21:37:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[21:37:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:37:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588)
[21:37:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573)
[21:37:06 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498)

**Comment by yuttyann** [comment]
I am not in an environment where I can debug at this time, so I cannot confirm this, but I suspect that it may have something to do with the priority of the plugin when it is activated.
Opening the downloaded "ScriptBlockPlus.jar" file and editing the "plugin.yml" in it may solve the problem.

Edit softdepend.
`
softdepend: [Vault, ScriptBlock, DiscordSRV, PlaceholderAPI]
`
↓
`
softdepend: [Vault, ScriptBlock, DiscordSRV, PlaceholderAPI, CMI(Enter the plugin id.)]
`
If this did not solve the problem, the Vault is most likely the cause.
In the meantime, when I have time, I will check for any problems on the plugin side.

**Comment by blankpager** [comment]
it works, thanks
