### ISSUE TITLE
Please update to 1.20.1

### ISSUE THREAD

**Issue by Shizuri23** [yuttyann/ScriptBlockPlus#46]
![c58a99faadbcf759c10d7dcd140f49d3](https://github.com/yuttyann/ScriptBlockPlus/assets/46082179/35556da8-44bb-4ea0-87ac-d1b804ac4b51)

**Comment by yuttyann** [comment]
I could not confirm that problem in my environment.
Can you send the entire error text?

**Comment by Shizuri23** [comment]
`[17:38:56 INFO]: [ScriptBlockPlus] Enabling ScriptBlockPlus v2.2.5
[17:38:56 ERROR]: Error occurred while enabling ScriptBlockPlus v2.2.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher.<clinit>(ReflectMatcher.java:39) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:213) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:129) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:124) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.utils.NMSHelper.build(NMSHelper.java:78) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.ScriptBlock.onEnable(ScriptBlock.java:84) ~[ScriptBlockPlus v2.2.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:643) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:554) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:639) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1105) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.util.Version.artifactVersion()" because the return value of "java.util.Map.get(Object)" is null
        at com.github.yuttyann.scriptblockplus.utils.collection.IntHashMap.<clinit>(IntHashMap.java:48) ~[ScriptBlockPlus v2.2.5.jar:?]
        ... 18 more
[17:38:56 INFO]: [ScriptBlockPlus] Disabling ScriptBlockPlus v2.2.5
[17:38:56 ERROR]: Error occurred (in the plugin loader) while disabling ScriptBlockPlus v2.2.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.github.yuttyann.scriptblockplus.ScriptBlock.onDisable(ScriptBlock.java:156) ~[ScriptBlockPlus v2.2.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:643) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:554) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:639) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1105) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:548) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:224) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at com.github.yuttyann.scriptblockplus.Scheduler.run(Scheduler.java:78) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.item.action.ScriptViewer.<clinit>(ScriptViewer.java:43) ~[ScriptBlockPlus v2.2.5.jar:?]
        ... 16 more`

**Comment by Shizuri23** [comment]
> I could not confirm that problem in my environment. Can you send the entire error text?

[17:38:56 INFO]: [ScriptBlockPlus] Enabling ScriptBlockPlus v2.2.5
[17:38:56 ERROR]: Error occurred while enabling ScriptBlockPlus v2.2.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher.<clinit>(ReflectMatcher.java:39) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:213) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:129) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:124) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.utils.NMSHelper.build(NMSHelper.java:78) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.ScriptBlock.onEnable(ScriptBlock.java:84) ~[ScriptBlockPlus v2.2.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:643) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:554) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:639) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1105) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.util.Version.artifactVersion()" because the return value of "java.util.Map.get(Object)" is null
        at com.github.yuttyann.scriptblockplus.utils.collection.IntHashMap.<clinit>(IntHashMap.java:48) ~[ScriptBlockPlus v2.2.5.jar:?]
        ... 18 more
[17:38:56 INFO]: [ScriptBlockPlus] Disabling ScriptBlockPlus v2.2.5
[17:38:56 ERROR]: Error occurred (in the plugin loader) while disabling ScriptBlockPlus v2.2.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.github.yuttyann.scriptblockplus.ScriptBlock.onDisable(ScriptBlock.java:156) ~[ScriptBlockPlus v2.2.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:643) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:554) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:639) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1105) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:548) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:224) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[leaves-1.20.1.jar:git-Leaves-"feb7fb4"]
        at com.github.yuttyann.scriptblockplus.Scheduler.run(Scheduler.java:78) ~[ScriptBlockPlus v2.2.5.jar:?]
        at com.github.yuttyann.scriptblockplus.item.action.ScriptViewer.<clinit>(ScriptViewer.java:43) ~[ScriptBlockPlus v2.2.5.jar:?]
        ... 16 more

**Comment by yuttyann** [comment]
Hmmm.
I still cannot reproduce that glitch in my environment.
I have verified the glitch with multiple versions and they are normal.

The solution is to re-download the latest plugin and re-download the server.

If this does not solve the problem, please describe your server details and the plugins you have installed.
