### ISSUE TITLE
ScriptBlockPlus cannot be loaded simultaneously with MiraiMC.

### ISSUE THREAD

**Issue by Shizuri23** [yuttyann/ScriptBlockPlus#49]
https://github.com/DreamVoid/MiraiMC
[17:27:25 INFO]: [ScriptBlockPlus] Enabling ScriptBlockPlus v2.2.6
[17:27:25 ERROR]: Error occurred while enabling ScriptBlockPlus v2.2.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher.<clinit>(ReflectMatcher.java:39) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:213) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:129) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:124) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.utils.NMSHelper.build(NMSHelper.java:78) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.ScriptBlock.onEnable(ScriptBlock.java:80) ~[ScriptBlockPlus v2.2.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:644) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:555) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1107) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.util.Version.artifactVersion()" because the return value of "java.util.Map.get(Object)" is null
        at com.github.yuttyann.scriptblockplus.utils.collection.IntHashMap.<clinit>(IntHashMap.java:48) ~[ScriptBlockPlus v2.2.6.jar:?]
        ... 18 more
[17:27:25 INFO]: [ScriptBlockPlus] Disabling ScriptBlockPlus v2.2.6
[17:27:25 ERROR]: Error occurred (in the plugin loader) while disabling ScriptBlockPlus v2.2.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.github.yuttyann.scriptblockplus.ScriptBlock.onDisable(ScriptBlock.java:149) ~[ScriptBlockPlus v2.2.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:644) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:555) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1107) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:548) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:224) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at com.github.yuttyann.scriptblockplus.Scheduler.run(Scheduler.java:78) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.item.action.ScriptViewer.<clinit>(ScriptViewer.java:43) ~[ScriptBlockPlus v2.2.6.jar:?]
        ... 16 more

**Comment by Shizuri23** [comment]
> https://github.com/DreamVoid/MiraiMC
> 
[17:27:25 INFO]: [ScriptBlockPlus] Enabling ScriptBlockPlus v2.2.6
[17:27:25 ERROR]: Error occurred while enabling ScriptBlockPlus v2.2.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher.<clinit>(ReflectMatcher.java:39) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:213) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:129) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:124) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.utils.NMSHelper.build(NMSHelper.java:78) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.ScriptBlock.onEnable(ScriptBlock.java:80) ~[ScriptBlockPlus v2.2.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:644) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:555) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1107) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.util.Version.artifactVersion()" because the return value of "java.util.Map.get(Object)" is null
        at com.github.yuttyann.scriptblockplus.utils.collection.IntHashMap.<clinit>(IntHashMap.java:48) ~[ScriptBlockPlus v2.2.6.jar:?]
        ... 18 more
[17:27:25 INFO]: [ScriptBlockPlus] Disabling ScriptBlockPlus v2.2.6
[17:27:25 ERROR]: Error occurred (in the plugin loader) while disabling ScriptBlockPlus v2.2.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.github.yuttyann.scriptblockplus.ScriptBlock.onDisable(ScriptBlock.java:149) ~[ScriptBlockPlus v2.2.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:644) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:555) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1107) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:548) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:224) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[leaves-1.20.1.jar:git-Leaves-"31672c1"]
        at com.github.yuttyann.scriptblockplus.Scheduler.run(Scheduler.java:78) ~[ScriptBlockPlus v2.2.6.jar:?]
        at com.github.yuttyann.scriptblockplus.item.action.ScriptViewer.<clinit>(ScriptViewer.java:43) ~[ScriptBlockPlus v2.2.6.jar:?]
        ... 16 more
