### ISSUE TITLE
Could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by Lostpart** [yuttyann/ScriptBlockPlus#6]
It seems almost exactly same error as #2  and #5 happens on v1.6.7

Server is 1.12 running on PFserver
The core file is here. (It is a. jar file, I rename it to .zip in order to upload)
[PFServer-cfdc1ad-server.jar.zip](https://github.com/yuttyann/ScriptBlockPlus/files/2761755/PFServer-cfdc1ad-server.jar.zip)

`[06:15:13] [ERROR]: Could not pass event PlayerMoveEvent to ScriptBlockPlus v1.6.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[JavaPluginLoader$1.class:git-cfdc1ad]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-cfdc1ad]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:489) [SimplePluginManager.class:git-cfdc1ad]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:474) [SimplePluginManager.class:git-cfdc1ad]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:738) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:34) [lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Rotation.func_148833_a(CPacketPlayer.java:153) [lk$c.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(Util.java:51) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:471) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:803) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:657) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at com.github.yuttyann.scriptblockplus.player.BaseSBPlayer.isOnline(BaseSBPlayer.java:104) ~[?:?]
        at com.github.yuttyann.scriptblockplus.player.BaseSBPlayer.getLocation(BaseSBPlayer.java:89) ~[?:?]
        at com.github.yuttyann.scriptblockplus.listener.ScriptWalkListener.onPlayerMoveEvent(ScriptWalkListener.java:29) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:288) ~[JavaPluginLoader$1.class:git-cfdc1ad]
        ... 15 more`

**Comment by Lostpart** [comment]
After some tests I found that it seems that this error only happens on the new players and only happened when the player first time join the server.
I don't know if this is a help to solve this problem

**Comment by yuttyann** [comment]
Since there is no environment to test play now, it will correspond after February at the earliest.
